name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:  # temporary: allows manual testing

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # required for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Install
        run: npm ci
      - name: Show package version
        run: node -p "require('./package.json').version"
      - name: Build
        run: npm run build
      - name: Verify package contents
        run: npm pack --dry-run
      - name: Verify NPM_TOKEN present
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN secret is missing. Add it in Settings > Secrets > Actions." >&2
            exit 1
          fi
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance || npm publish --access public
